import { useEffect, useMemo, useState } from "react";
import { api } from "./api.js";

const initialMembers = [
  { id: 1, name: "Aarav Sharma", countryCode: "+91", phone: "98765 43210", tier: "Gold", points: 1840, spend: 18750, joined: "12 Jan 2026" },
  { id: 2, name: "Meera Iyer", countryCode: "+91", phone: "98450 11882", tier: "Silver", points: 620, spend: 7350, joined: "04 Mar 2026" },
  { id: 3, name: "Rahul Verma", countryCode: "+91", phone: "99887 22014", tier: "Regular", points: 180, spend: 1800, joined: "18 May 2026" },
  { id: 4, name: "Nisha Patel", countryCode: "+91", phone: "99115 83420", tier: "Silver", points: 940, spend: 9920, joined: "02 Feb 2026" },
];
const transactions = [
  { title: "Cappuccino & croissant", date: "Today, 10:42 AM", points: 42, type: "earn" },
  { title: "Reward redeemed", date: "Yesterday, 4:17 PM", points: -150, type: "redeem" },
  { title: "Iced latte", date: "12 Sep, 1:06 PM", points: 30, type: "earn" },
];

const money = value => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value);
const tierClass = tier => tier.toLowerCase();

function App() {
  const [role, setRole] = useState(null);
  const [loginRole, setLoginRole] = useState(null);
  const [token, setToken] = useState(null);
  const [loginError, setLoginError] = useState("");
  const [page, setPage] = useState("home");
  const [members, setMembers] = useState(initialMembers);
  const [selectedId, setSelectedId] = useState(1);
  const [query, setQuery] = useState("");
  const [tierFilter, setTierFilter] = useState("all");
  const [modal, setModal] = useState(null);
  const [toast, setToast] = useState("");
  const selected = members.find(member => member.id === selectedId) ?? members[0];
  const notify = message => { setToast(message); window.setTimeout(() => setToast(""), 3000); };
  const signOut = () => { setRole(null); setLoginRole(null); setToken(null); setLoginError(""); setPage("home"); };
  const updateMember = (id, changes) => setMembers(current => current.map(member => member.id === id ? { ...member, ...changes } : member));

  useEffect(() => {
    if (!token || !role) return;
    const loadData = async () => {
      try {
        if (role === "customer") {
          const data = await api.customerDashboard(token);
          const member = data.member;
          setMembers(current => [{ id: member.id, name: member.name, countryCode: member.country_code, phone: member.phone_number, tier: member.tier[0] + member.tier.slice(1).toLowerCase(), points: member.points_balance, spend: member.lifetime_spend_paise / 100, joined: member.created_at.slice(0, 10) }, ...current.slice(1)]);
        } else {
          const data = await api.staffMembers(token);
          if (data.items.length) setMembers(data.items.map(member => ({ id: member.id, name: member.name, countryCode: member.country_code, phone: member.phone_number, tier: member.tier[0] + member.tier.slice(1).toLowerCase(), points: member.points_balance, spend: member.lifetime_spend_paise / 100, joined: member.created_at.slice(0, 10) })));
        }
      } catch (error) { notify(error.message); }
    };
    loadData();
  }, [token, role]);

  if (!role && !loginRole) return <RoleSelection onChoose={setLoginRole} />;
  if (!role) return <Login role={loginRole} error={loginError} onBack={() => { setLoginRole(null); setLoginError(""); }} onSignIn={async ({ email, password }) => {
    try {
      setLoginError("");
      const session = await api.login(email, password);
      const returnedRole = session.role.toLowerCase();
      if (returnedRole !== loginRole) throw new Error(`This account is registered as ${returnedRole}, not ${loginRole}.`);
      setToken(session.access_token); setRole(returnedRole); setLoginRole(null); setPage("home");
    } catch (error) { setLoginError(error.message); }
  }} />;

  const nav = role === "customer" ? [{ key: "home", icon: "⌂", label: "My wallet" }, { key: "history", icon: "◷", label: "Activity" }] : [{ key: "home", icon: "⌂", label: "Dashboard" }, { key: "members", icon: "♙", label: "Members" }, { key: "bills", icon: "▤", label: "Bills" }];
  let content;
  if (role === "customer") content = page === "history" ? <History /> : <CustomerDashboard member={members[0]} openRedeem={() => setModal("redeem")} setPage={setPage} />;
  else if (page === "members") content = <MemberDirectory members={members} query={query} tierFilter={tierFilter} setQuery={setQuery} setTierFilter={setTierFilter} openMember={id => { setSelectedId(id); setPage("detail"); }} openNew={() => setModal("new-member")} />;
  else if (page === "detail") content = <MemberDetail member={selected} back={() => setPage("members")} purchase={() => setModal("purchase")} redeem={() => setModal("redeem")} />;
  else if (page === "bills") content = <Bills openPurchase={() => setModal("purchase")} notify={notify} />;
  else content = <StaffDashboard openPurchase={() => setModal("purchase")} findMember={phone => { const found = members.find(member => member.phone.replace(/\D/g, "").includes(phone.replace(/\D/g, ""))); if (found) { setSelectedId(found.id); setPage("detail"); } else notify("No matching member found."); }} setPage={setPage} />;

  return <><Shell nav={nav} page={page} setPage={setPage} role={role} signOut={signOut}>{content}</Shell>{modal === "purchase" && <PurchaseModal members={members} close={() => setModal(null)} save={(id, amount) => { const member = members.find(item => item.id === id); const spend = member.spend + amount; updateMember(id, { spend, points: member.points + Math.round(amount / 10), tier: spend >= 15000 ? "Gold" : spend >= 5000 ? "Silver" : "Regular" }); setModal(null); notify("Purchase saved and points added."); }} />}{modal === "redeem" && <RedeemModal member={role === "customer" ? members[0] : selected} close={() => setModal(null)} redeem={points => { const member = role === "customer" ? members[0] : selected; if (points > member.points || points % 10) return notify("Use a valid multiple of 10 points."); updateMember(member.id, { points: member.points - points }); setModal(null); notify(`Redeemed ${points} points (${money(points / 10)} value).`); }} />}{modal === "new-member" && <NewMemberModal close={() => setModal(null)} save={member => { setMembers(items => [...items, { ...member, id: Date.now(), tier: "Regular", points: 0, spend: 0, joined: "Today" }]); setModal(null); notify("New member created."); }} />}{toast && <div className="toast-root"><div className="toast success">{toast}</div></div>}</>;
}

function RoleSelection({ onChoose }) { return <section className="role-page"><div className="brand-panel"><div><div className="brand-mark"><span className="cup">☕</span> BrewRewards</div><h1>Every coffee should feel rewarding.</h1><p>A warm loyalty experience for customers and a reliable counter for your café team.</p></div><small>Designed for neighbourhood cafés, built for regulars.</small></div><div className="role-content"><div className="role-card"><p className="eyebrow">Welcome to BrewRewards</p><h2>How would you like to continue?</h2><p className="subtle">Choose your space to view rewards or manage the café counter.</p><div className="role-options"><button className="role-option" onClick={() => onChoose("customer")}><span className="role-icon">✦</span><span><strong>I&apos;m a customer</strong><span>View your points and redeem rewards</span></span><span className="arrow">→</span></button><button className="role-option" onClick={() => onChoose("staff")}><span className="role-icon">☕</span><span><strong>I&apos;m café staff</strong><span>Manage members, purchases, and bills</span></span><span className="arrow">→</span></button></div></div></div></section>; }
function Login({ role, error, onBack, onSignIn }) { const customer = role === "customer"; const [email, setEmail] = useState(customer ? "aarav@brewrewards.test" : "admin@brewrewards.test"); const [password, setPassword] = useState(customer ? "BrewCustomer#2026" : "BrewAdmin#2026"); return <section className="role-page"><div className="brand-panel"><div><div className="brand-mark"><span className="cup">☕</span> BrewRewards</div><h1>{customer ? "Your next reward is brewing." : "A calmer café counter."}</h1><p>{customer ? "See your points, tier, and free-item rewards in one place." : "Manage purchases, members, and receipts with confidence."}</p></div><small>Harbour Brew Café</small></div><div className="role-content"><div className="role-card"><button className="text-button" onClick={onBack}>← Back to role selection</button><p className="eyebrow" style={{ marginTop: "1.5rem" }}>{customer ? "Customer sign in" : "Staff sign in"}</p><h2>Welcome back</h2><p className="subtle">Testing details are prefilled for this local demo.</p><form onSubmit={event => { event.preventDefault(); onSignIn({ email, password }); }} style={{ marginTop: "1.1rem" }}><div className="form-group"><label>Email</label><input type="email" required value={email} onChange={event => setEmail(event.target.value)} /></div><div className="form-group"><label>Password</label><input type="password" required value={password} onChange={event => setPassword(event.target.value)} /></div>{error && <p className="form-error">{error}</p>}<button className="button primary" style={{ width: "100%", marginTop: ".4rem" }}>Sign in</button></form></div></div></section>; }
function Shell({ nav, page, setPage, role, signOut, children }) { return <div className="app-shell"><aside className="sidebar"><div className="brand-mark"><span className="cup">☕</span> BrewRewards</div><nav className="nav-list">{nav.map(item => <button key={item.key} className={`nav-link ${page === item.key ? "active" : ""}`} onClick={() => setPage(item.key)}><span>{item.icon}</span>{item.label}</button>)}</nav><div className="sidebar-bottom"><div className="profile-mini"><strong>{role === "staff" ? "Priya · Barista" : "Aarav Sharma"}</strong>{role === "staff" ? "Harbour Brew Café" : "Gold member"}</div><button className="nav-link" onClick={signOut}>↩ Sign out</button></div></aside><div className="workspace"><header className="topbar"><div className="mobile-brand brand-mark"><span className="cup">☕</span> BrewRewards</div><h1>{role === "staff" ? "Harbour Brew Café" : "Your rewards"}</h1></header><main className="content">{children}</main></div></div>; }
function TransactionRows() { return transactions.map(transaction => <div className="transaction" key={`${transaction.title}-${transaction.date}`}><div className="transaction-icon">{transaction.type === "earn" ? "☕" : "✦"}</div><div><strong>{transaction.title}</strong><small>{transaction.date}</small></div><div className={transaction.points > 0 ? "positive" : "negative"}>{transaction.points > 0 ? "+" : ""}{transaction.points} pts</div></div>); }
function CustomerDashboard({ member, openRedeem, setPage }) { const progress = Math.min(100, Math.round(member.spend / 15000 * 100)); return <><div className="page-heading"><div><p className="eyebrow">Good morning, Aarav</p><h2>Your rewards wallet</h2><p>Every visit gets you closer to your next favourite coffee.</p></div><button className="button primary" onClick={openRedeem}>Redeem reward</button></div><div className="grid two-col"><div className="grid"><section className="card wallet-card"><span className={`tier-pill ${tierClass(member.tier)}`}>● {member.tier} member</span><div className="label" style={{ marginTop: "1.3rem" }}>Available points</div><div className="wallet-points">{member.points}</div><div className="wallet-value">Worth {money(member.points / 10)} in free items</div></section><section className="card"><div className="section-title"><h3>Recent activity</h3><button className="text-button" onClick={() => setPage("history")}>View all</button></div><TransactionRows /></section></div><div className="grid"><section className="card"><div className="section-title"><h3>Tier progress</h3><span className={`tier-pill ${tierClass(member.tier)}`}>{member.tier}</span></div><p className="subtle">You&apos;ve reached our highest tier—enjoy faster rewards on every visit.</p><div className="progress-track"><div className="progress-fill" style={{ width: `${progress}%` }} /></div><div className="progress-copy"><span>{money(member.spend)} lifetime spend</span><span>Gold achieved</span></div></section><section className="card"><div className="section-title"><h3>How rewards work</h3></div><div className="info-list"><div className="info-item"><span>Earn on every ₹10 purchase</span><strong>1+ point</strong></div><div className="info-item"><span>Reward value</span><strong>10 pts = ₹1</strong></div><div className="info-item"><span>Free redemptions</span><strong>No new points</strong></div></div></section></div></div></>; }
function History() { return <><div className="page-heading"><div><p className="eyebrow">Your rewards</p><h2>Activity history</h2><p>Every point earned and redeemed in one place.</p></div></div><section className="card"><div className="section-title"><h3>All transactions</h3><span className="subtle">5 entries</span></div><TransactionRows /></section></>; }
function StaffDashboard({ openPurchase, findMember, setPage }) { const [phone, setPhone] = useState(""); return <><div className="page-heading"><div><p className="eyebrow">Harbour Brew Café</p><h2>Good morning, Priya</h2><p>Here&apos;s how your rewards programme is doing today.</p></div><button className="button primary" onClick={openPurchase}>＋ Record purchase</button></div><div className="grid stats">{[["Active members", "1,248", "↑ 24 this month"], ["Purchases today", "86", "↑ 12% vs yesterday"], ["Points issued today", "2,940", "₹294 reward value"], ["Redemptions today", "14", "₹86 redeemed"]].map(stat => <section className="card stat-card" key={stat[0]}><div className="label">{stat[0]}</div><div className="value">{stat[1]}</div><div className="hint">{stat[2]}</div></section>)}</div><div className="grid two-col" style={{ marginTop: "1.2rem" }}><section className="card"><div className="section-title"><h3>Recent counter activity</h3><button className="text-button" onClick={() => setPage("members")}>View members</button></div><TransactionRows /></section><section className="card"><div className="section-title"><h3>Quick member lookup</h3></div><p className="subtle">Find a customer by phone number to record a purchase or reward.</p><div className="search-row"><div className="search-field"><span>⌕</span><input value={phone} onChange={event => setPhone(event.target.value)} placeholder="Phone number" /></div><button className="button primary" onClick={() => findMember(phone)}>Search</button></div></section></div></>; }
function MemberDirectory({ members, query, tierFilter, setQuery, setTierFilter, openMember, openNew }) { const visible = useMemo(() => members.filter(member => (member.name.toLowerCase().includes(query.toLowerCase()) || member.phone.replace(/\D/g, "").includes(query.replace(/\D/g, ""))) && (tierFilter === "all" || member.tier === tierFilter)), [members, query, tierFilter]); return <><div className="page-heading"><div><p className="eyebrow">Member directory</p><h2>Find a regular</h2><p>Search the loyalty programme by name or phone number.</p></div><button className="button primary" onClick={openNew}>＋ Add member</button></div><section className="card"><div className="search-row"><div className="search-field"><span>⌕</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search name or phone number" /></div><select className="filter-select" value={tierFilter} onChange={event => setTierFilter(event.target.value)}><option value="all">All tiers</option><option>Regular</option><option>Silver</option><option>Gold</option></select></div><div className="member-table"><div className="member-header"><span>Member</span><span>Phone</span><span>Tier</span><span>Points</span><span>Lifetime spend</span></div>{visible.map(member => <button className="member-row" key={member.id} onClick={() => openMember(member.id)}><span><strong>{member.name}</strong><small>Joined {member.joined}</small></span><span>{member.countryCode} {member.phone}</span><span><span className={`tier-pill ${tierClass(member.tier)}`}>{member.tier}</span></span><span>{member.points} pts</span><span>{money(member.spend)}</span></button>)}</div></section></>; }
function MemberDetail({ member, back, purchase, redeem }) { return <><div className="page-heading"><div className="member-hero"><div className="avatar">{member.name.split(" ").map(item => item[0]).join("")}</div><div className="member-meta"><h2>{member.name}</h2><p>{member.countryCode} {member.phone} · Member since {member.joined}</p><span className={`tier-pill ${tierClass(member.tier)}`}>● {member.tier}</span></div><div className="detail-actions"><button className="button secondary" onClick={back}>Back</button><button className="button primary" onClick={purchase}>Record purchase</button></div></div></div><div className="grid stats"><Stat label="Available balance" value={`${member.points} pts`} hint={`Worth ${money(member.points / 10)}`} /><Stat label="Lifetime spend" value={money(member.spend)} hint="Tier qualification total" /><Stat label="Current tier" value={member.tier} hint="Keeps growing with every visit" /><Stat label="Member since" value={member.joined} hint="Loyalty member" /></div><div className="grid two-col" style={{ marginTop: "1.2rem" }}><section className="card"><div className="section-title"><h3>Point history</h3><button className="text-button" onClick={redeem}>Redeem points</button></div><TransactionRows /></section><section className="card"><div className="section-title"><h3>Member details</h3></div><div className="info-list"><div className="info-item"><span>Country code</span><strong>{member.countryCode}</strong></div><div className="info-item"><span>Phone</span><strong>{member.phone}</strong></div><div className="info-item"><span>Reward conversion</span><strong>10 pts = ₹1</strong></div></div></section></div></>; }
function Stat({ label, value, hint }) { return <section className="card stat-card"><div className="label">{label}</div><div className="value">{value}</div><div className="hint">{hint}</div></section>; }
function Bills({ openPurchase, notify }) { return <><div className="page-heading"><div><p className="eyebrow">Counter receipt</p><h2>Generate a bill</h2><p>Create a clear receipt for a customer purchase.</p></div><button className="button primary" onClick={openPurchase}>New purchase</button></div><section className="card receipt"><div className="receipt-head"><h3>Harbour Brew Café</h3><p className="subtle">17 Beach Road, Chennai</p></div>{[["Receipt no.", "HB-2026-0917"], ["Customer", "Aarav Sharma"], ["Cappuccino × 2", "₹360"], ["Almond croissant × 1", "₹180"], ["Reward discount", "−₹60"]].map(line => <div className="receipt-line" key={line[0]}><span>{line[0]}</span><strong>{line[1]}</strong></div>)}<div className="receipt-total"><span>Total paid</span><span>₹480</span></div><div className="receipt-note">48 points will be added after this purchase.</div><div className="modal-actions"><button className="button secondary" onClick={() => window.print()}>Print receipt</button><button className="button primary" onClick={() => notify("Bill saved. PDF generation will be connected to FastAPI.")}>Save bill</button></div></section></>; }
function Modal({ children, close }) { return <div className="modal-backdrop" onClick={event => { if (event.target === event.currentTarget) close(); }}><section className="modal" role="dialog" aria-modal="true">{children}</section></div>; }
function PurchaseModal({ members, close, save }) { const [memberId, setMemberId] = useState(members[0].id); const [amount, setAmount] = useState(""); return <Modal close={close}><h3>Record a purchase</h3><p>Points are calculated after the bill is saved.</p><form onSubmit={event => { event.preventDefault(); save(Number(memberId), Number(amount)); }}><div className="form-group"><label>Member</label><select value={memberId} onChange={event => setMemberId(event.target.value)}>{members.map(member => <option key={member.id} value={member.id}>{member.name} · {member.points} pts</option>)}</select></div><div className="form-group"><label>Purchase amount (₹)</label><input type="number" min="1" value={amount} onChange={event => setAmount(event.target.value)} required /></div><div className="modal-actions"><button type="button" className="button secondary" onClick={close}>Cancel</button><button className="button primary">Save purchase</button></div></form></Modal>; }
function RedeemModal({ member, close, redeem }) { const [points, setPoints] = useState(""); return <Modal close={close}><h3>Redeem points</h3><p>{member.points} points are available, worth up to {money(member.points / 10)} in free items.</p><form onSubmit={event => { event.preventDefault(); redeem(Number(points)); }}><div className="form-group"><label>Points to redeem</label><input type="number" min="10" max={member.points} step="10" value={points} onChange={event => setPoints(event.target.value)} required /></div><div className="modal-actions"><button type="button" className="button secondary" onClick={close}>Cancel</button><button className="button danger">Confirm redemption</button></div></form></Modal>; }
function NewMemberModal({ close, save }) { const [form, setForm] = useState({ name: "", countryCode: "+91", phone: "" }); return <Modal close={close}><h3>Add a member</h3><p>Phone number is stored separately from the country code.</p><form onSubmit={event => { event.preventDefault(); save(form); }}>{[["name", "Full name"], ["countryCode", "Country code"], ["phone", "Phone number"]].map(([key, label]) => <div className="form-group" key={key}><label>{label}</label><input required value={form[key]} onChange={event => setForm({ ...form, [key]: event.target.value })} /></div>)}<div className="modal-actions"><button type="button" className="button secondary" onClick={close}>Cancel</button><button className="button primary">Create member</button></div></form></Modal>; }

export default App;
